### ISSUE TITLE
Where are the models on Linux?

### ISSUE THREAD

**Issue by dzy1128** [wujm424606/ComfyUi-Ollama-YN#10]
Where is the model placed on Linux, and how do I change the environment variables?

**Comment by markawonge** [comment]
First, you need to install the Ollama CLI by running the following command:
`curl -fsSL https://ollama.com/install.sh | sh`
Next, you can pull the desired LLM models. The following command is just an example:
`ollama pull llama3.1`
Feel free to replace it with the name of any other model you need.

**Comment by dzy1128** [comment]
Thank you.
