### ISSUE TITLE
找不到模型

### ISSUE THREAD

**Issue by dzy1128** [wujm424606/ComfyUi-Ollama-YN#11]
Error occurred when executing OllamaGenerate:

File "/data/sdweb/ComfyUI/execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/data/sdweb/ComfyUI/execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/data/sdweb/ComfyUI/execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "/data/sdweb/ComfyUI/execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "/data/sdweb/ComfyUI/custom_nodes/ComfyUi-Ollama-YN/CompfyuiOllama.py", line 137, in ollama_generate
response = client.generate(model=model, prompt=prompt, options=options, keep_alive=keep_alive)
File "/home/xiaokuai/.local/lib/python3.10/site-packages/ollama/_client.py", line 163, in generate
return self._request_stream(
File "/home/xiaokuai/.local/lib/python3.10/site-packages/ollama/_client.py", line 99, in _request_stream
return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
File "/home/xiaokuai/.local/lib/python3.10/site-packages/ollama/_client.py", line 75, in _request
raise ResponseError(e.response.text, e.response.status_code) from None

**Comment by wujm424606** [comment]
我进行了一次大的更新，现在手动分类后会自动加载已经下载的模型在模型列表里，也提供了删除模型的节点，详情可以看介绍文档

**Comment by dzy1128** [comment]
更新之后报这个错：
# ComfyUI Error Report
## Error Details
- **Node Type:** MyOllamaGenerateAdvance
- **Exception Type:** ollama._types.ResponseError
- **Exception Message:** 
## Stack Trace
```
  File "/data/sdweb/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/data/sdweb/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/data/sdweb/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/data/sdweb/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/data/sdweb/ComfyUI/custom_nodes/ComfyUi-Ollama-YN/ollama_main.py", line 435, in ollama_generate_advance
    response = client.generate(model=model, system=system, prompt=prompt, keep_alive=keep_alive, context=context, options=options)

  File "/home/xiaokuai/.local/lib/python3.10/site-packages/ollama/_client.py", line 163, in generate
    return self._request_stream(

  File "/home/xiaokuai/.local/lib/python3.10/site-packages/ollama/_client.py", line 99, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()

  File "/home/xiaokuai/.local/lib/python3.10/site-packages/ollama/_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None

```
## System Information
- **ComfyUI Version:** v0.2.2-33-gf6b7194
- **Arguments:** main.py --port 8188 --listen=0.0.0.0
- **OS:** posix
- **Python Version:** 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.0+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25282281472
  - **VRAM Free:** 24855642112
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

**Comment by wujm424606** [comment]
> 更新之后报这个错：
> 
> # ComfyUI Error Report
> ## Error Details
> * **Node Type:** MyOllamaGenerateAdvance
> * **Exception Type:** ollama._types.ResponseError
> * **Exception Message:**
> 
> ## Stack Trace
> ```
>   File "/data/sdweb/ComfyUI/execution.py", line 323, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
> 
>   File "/data/sdweb/ComfyUI/execution.py", line 198, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
> 
>   File "/data/sdweb/ComfyUI/execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
> 
>   File "/data/sdweb/ComfyUI/execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
> 
>   File "/data/sdweb/ComfyUI/custom_nodes/ComfyUi-Ollama-YN/ollama_main.py", line 435, in ollama_generate_advance
>     response = client.generate(model=model, system=system, prompt=prompt, keep_alive=keep_alive, context=context, options=options)
> 
>   File "/home/xiaokuai/.local/lib/python3.10/site-packages/ollama/_client.py", line 163, in generate
>     return self._request_stream(
> 
>   File "/home/xiaokuai/.local/lib/python3.10/site-packages/ollama/_client.py", line 99, in _request_stream
>     return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
> 
>   File "/home/xiaokuai/.local/lib/python3.10/site-packages/ollama/_client.py", line 75, in _request
>     raise ResponseError(e.response.text, e.response.status_code) from None
> ```
> 
> ## System Information
> * **ComfyUI Version:** v0.2.2-33-gf6b7194
> * **Arguments:** main.py --port 8188 --listen=0.0.0.0
> * **OS:** posix
> * **Python Version:** 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
> * **Embedded Python:** false
> * **PyTorch Version:** 2.4.0+cu124
> 
> ## Devices
> * **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
>   
>   * **Type:** cuda
>   * **VRAM Total:** 25282281472
>   * **VRAM Free:** 24855642112
>   * **Torch VRAM Total:** 0
>   * **Torch VRAM Free:** 0

是用的远程客户端还是本地？可以先试验一下删除改插件再重装看下是否会报相同的错误

**Comment by wujm424606** [comment]
这个插件使用模型会从本地建立一个客户端也就是http://127.0.0.1:11434，用来执行ollama模型的操作，你可以看下这个端口是否被占用，如果被占用，手动更改成一个没被占用的端口，还有就是下载模型最好开魔法否则可能下载不动模型

**Comment by dzy1128** [comment]
ollama在服务器上是正常运行的，我之前使用的节点是可以正常访问到那边的模型的，换成您这个现在就是报这个错，日志里还有显示这个：HTTP Request: POST http://*****:11434/api/generate "HTTP/1.1 502 Bad Gateway"，ip我换成*了

**Comment by wujm424606** [comment]
> ollama在服务器上是正常运行的，我之前使用的节点是可以正常访问到那边的模型的，换成您这个现在就是报这个错，日志里还有显示这个：HTTP Request: POST http://*****:11434/api/generate "HTTP/1.1 502 Bad Gateway"，ip我换成*了

请问能发送一份日志文件吗？这个回复显示的只有*， 还有就是服务器的端口使用默认端口就是11434是否生效？

**Comment by wujm424606** [comment]
您是在云服务器运行的这个插件对吗？

**Comment by dzy1128** [comment]
不算云服务器，公司自己部署的服务器。

**Comment by dzy1128** [comment]
got prompt
advance_model:  llama3.1:latest
HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 502 Bad Gateway"
!!! Exception during processing !!! 
Traceback (most recent call last):
  File "/data/sdweb/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/data/sdweb/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/data/sdweb/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/data/sdweb/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/data/sdweb/ComfyUI/custom_nodes/ComfyUi-Ollama-YN/ollama_main.py", line 435, in ollama_generate_advance
    response = client.generate(model=model, system=system, prompt=prompt, keep_alive=keep_alive, context=context, options=options)
  File "/home/xiaokuai/.local/lib/python3.10/site-packages/ollama/_client.py", line 163, in generate
    return self._request_stream(
  File "/home/xiaokuai/.local/lib/python3.10/site-packages/ollama/_client.py", line 99, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
  File "/home/xiaokuai/.local/lib/python3.10/site-packages/ollama/_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError

Prompt executed in 1.25 seconds
这是完整的日志

**Comment by dzy1128** [comment]
![image](https://github.com/user-attachments/assets/a29c4fa6-7a9b-4534-a625-8e887875f2f0)

**Comment by wujm424606** [comment]
![image](https://github.com/user-attachments/assets/1ff02bd7-2404-4d15-806b-04c9ee8a87a9)
这个url部分的http://127.0.0.1: 部分替换成你自己的ip然后运行也会报错吗？

**Comment by dzy1128** [comment]
是的，会报错，我目前使用的就是自己的ip。

**Comment by dzy1128** [comment]
监听那边也换成0.0.0.0了

**Comment by wujm424606** [comment]
运行的模型是已经下载完成了对吗？ 如果你是在更新之前下载的模型需要重新导入到category.csv文件中，详情可见tips

**Comment by dzy1128** [comment]
好，我去试试

**Comment by wujm424606** [comment]
还有就是我一般都是在本地运行的，本地的ip一般不会报这个错，正常的话，如果你使用默认的模型进行运行，如果你没有下载这个模型，会运行ollama pull + 模型名进行自动下载到本地，然后会调用client的ip进行运行这个模型，这个是一个实现的逻辑，也就是HTTP Request: POST http://自己设置的ip/api/generate "HTTP/1.1 去运行，正常会显示如下结果
![image](https://github.com/user-attachments/assets/959e91b7-7003-4c21-9825-cf1113c43638)

**Comment by dzy1128** [comment]
还是会报错，我下载好的模型在csv文件里是有的。不在csv里的模型，我加进去之后节点并没有识别到

**Comment by wujm424606** [comment]
https://github.com/stavsap/comfyui-ollama/issues/37 参考下这个不知道能不能解决你的问题

**Comment by dzy1128** [comment]
解决了，非常感谢您
