### ISSUE TITLE
When I select those default models, it wont load

### ISSUE THREAD

**Issue by Orenji-Tangerine** [wujm424606/ComfyUi-Ollama-YN#13]
For example, minicpm-v,

![image](https://github.com/user-attachments/assets/6e2392e3-817c-4004-a42b-216275e57e54)

I then type the model name in the extra_model, then it loads fine
![image](https://github.com/user-attachments/assets/ca5578bb-64d8-4875-870f-052d9be52d44)

By the way, I notice this on the console screen. As I have previously downloaded this model via Powershell with command line: ollama run minicpm-v, does the message on the console imply that it downloads a new model and place onto ComfyUI folder or it just runs from the Ollama cache in the system drive?
![image](https://github.com/user-attachments/assets/08d5fd50-3039-407c-98a8-695e2579be53)

![image](https://github.com/user-attachments/assets/c1c411da-0153-45c7-9ce3-1f2b626daec9)

**Comment by wujm424606** [comment]
The overall operating logic is like this: If you click to load the default model that has not been downloaded, a subprocess will be opened to run the ollama pull model command, which means that you use ollama to download the model to the specified location you have set, and then the client will be called to send a post request to run the model.  If you are downloading and running an additional model, fill in the extra model.   So normally, there should be no situation where the default model cannot be downloaded. If this happens, you can try to uninstall the plug-in and then reinstall the plug-in. For importing previously downloaded models, you can refer to Tips for explanation. Simply put, model identification relies on the category.csv file. You need to import the name of the downloaded model into the category.csv file

**Comment by Orenji-Tangerine** [comment]
Thanks for your reply.

Now the issue is
1. I cannot just get the node to download the model
2. I have to manually download via command line
3. When an existing model is already in the drive, by selecting the model, it will not load, I will have to type the model name in the extra_model in order for it to load

For example, I want to try out this Moondream model, the node returns with error
![image](https://github.com/user-attachments/assets/2e57ed6b-5d25-422b-b5ec-6adb7424a274)

Error on the console screen
![image](https://github.com/user-attachments/assets/0a4f6385-e3b7-4f6a-ad31-4af2e5b7ae01)

I will have to download via command line ollama run moondream
![image](https://github.com/user-attachments/assets/302683a1-7245-433a-a906-f133c8027bdd)

I am still facing the same error like the above
![image](https://github.com/user-attachments/assets/4c629723-6921-434f-ab55-2d3ecbf85a38)

I will then type the model name in the box
![image](https://github.com/user-attachments/assets/3bcdd544-7939-448e-9dae-63a4f5f611cd)

And the console screen will have this (I suppose the model is stored in the default directory of Ollama)
![image](https://github.com/user-attachments/assets/41e72219-b5e3-4519-8666-e38a61e33342)

I dont see any subprocess though. I have updated the list in the CSV and I will still need to type the model name in the extra_model for it to run.

My Python environment is 3.10.11, does it matter?

**Comment by wujm424606** [comment]
![image](https://github.com/user-attachments/assets/47195e95-21c3-4197-a495-26e00546c042)This error feels a bit strange. Your question shows that the model name clicked was basically obtained into the program. The feeling of obtaining the model name is ""

**Comment by wujm424606** [comment]
![image](https://github.com/user-attachments/assets/951f8ce8-6a36-433b-b689-db5adea3e87a)
Normally, the correct model name is obtained here, but instead of transmitting the correct model name, you only output:latest     I normally run on a win11 computer and did not report this error

**Comment by wujm424606** [comment]
I seem to understand that when you use the default name, you need to keep extra_model equal to none

**Comment by wujm424606** [comment]
![image](https://github.com/user-attachments/assets/82ce24e0-f84e-4ab8-a1f8-c66ff01e3a21)

**Comment by wujm424606** [comment]
![image](https://github.com/user-attachments/assets/4b287e8d-d711-46b4-b858-8f06b7fb45cc)

**Comment by wujm424606** [comment]
I set extra_model to none by default in the program, but I don't know why your display is null

**Comment by Orenji-Tangerine** [comment]
An error like the above will prompt, if I leave the extra_model empty, be it the default listed model or any existing models or new models that I download. In other words, will need to input model name in the extra_model, for all default listed model, existing models downloaded.

And for the download of new model function via the extra_model, it just doesn't happen.

By the way, the node default behaviour is that it will run the model by default? Because I will still need to use the usual way of ollama run model via command line.

**Comment by wujm424606** [comment]
I mean when you use the default model, fill in the string none in extra_model.

**Comment by wujm424606** [comment]
I mean when you use the default model, fill in the string none in extra_model

**Comment by wujm424606** [comment]
Instead of deleting the extra_model section as empty

**Comment by wujm424606** [comment]
You only need to change the value of extra_model if you want to download a new model in addition to the default model. Of course, you can download models using the previous method, but you need to remember to refer to tips and fill in the name of the newly downloaded model in category.csv. Using extra_model to download will automatically complete the filling in category.csv, eliminating the trouble of manual work

**Comment by Orenji-Tangerine** [comment]
![image](https://github.com/user-attachments/assets/24930aeb-960c-4239-a507-3e59da8de8bc)

This node by default has None in the field. It is the same if None is input in the field. I will have to specifically type "llava" in extra_model, followed by "ollama run llava" via command line before I queue prompt.

**Comment by wujm424606** [comment]
Fill in none instead of None

**Comment by wujm424606** [comment]
![image](https://github.com/user-attachments/assets/45a73907-2a40-4c89-9209-bcba8e76f867)
Normally, as long as you reload the imported node, the extra model will display none.

**Comment by Orenji-Tangerine** [comment]
OK, now it solves the mystery, my bad. It is the word 'none'

Haha, thanks for your time! Now this works great!

> ![image](https://private-user-images.githubusercontent.com/38379474/369014842-45a73907-2a40-4c89-9209-bcba8e76f867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTM4MTgsIm5iZiI6MTcyNjc1MzUxOCwicGF0aCI6Ii8zODM3OTQ3NC8zNjkwMTQ4NDItNDVhNzM5MDctMmE0MC00Yzg5LTkyMDktYmNiYThlNzZmODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDEzNDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYzE4M2E2MGFkMDk4YjMyZDFmMDYyYWJiZDFiNTFlYzNlNGUxMTkxMjdhOTMyODE1ZmIwZjRlYzE5ZjU3N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8LXEwty_Nv8kFIbYWd4EVo_gmcQwn0au0EkdRCw-4Bc) Normally, as long as you reload the imported node, the extra model will display none.
