### ISSUE TITLE
Image input doesn't work

### ISSUE THREAD

**Issue by bosbrand** [wujm424606/ComfyUi-Ollama-YN#3]
If I ask about the image connected to the image input, the bot says there wasn't any image input.

**Comment by wujm424606** [comment]
![image](https://github.com/wujm424606/ComfyUi-Ollama-YN/assets/38379474/1286a78d-f35c-4d51-a38d-5ae897924706)
I test it, it can work well

**Comment by oylbin** [comment]
> If I ask about the image connected to the image input, the bot says there wasn't any image input.

I had the same problem when I use model `llama3:8b-instruct-q4_K_M`.
Problem had been solved after I changed to model `llava`.
I think `llama3:8b-instruct-q4_K_M` can not handle image input.
