### ISSUE TITLE
HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 404 Not Found" !!! Exception during processing!!! model 'llava' not found, try pulling it first

### ISSUE THREAD

**Issue by cgl13207205048** [wujm424606/ComfyUi-Ollama-YN#6]
怎么找模型的位置，模型名那一栏怎么填才对

**Comment by wujm424606** [comment]
模型的位置，如果你没有自己定义路径的话，默认路径会在C盘的用户名文件下的.ollama文件夹里，模型名的填写方式就是你之前下载模型的方式不是ollama run +模型， 比如ollama run llama3，最后的llama3就是模型名，具体下载模型的网址是 https://ollama.com/library    ，想下什么模型就搜索即可，换成对应的模型名就是了，然后记得在comfyui界面运行的时候也把模型名替换成相同即可调用
