### ISSUE TITLE
无法自行输入模型名称

### ISSUE THREAD

**Issue by git2306** [wujm424606/ComfyUi-Ollama-YN#7]
您好, 使用 My Ollama Generate Advance 与 My Ollama Special Generate Advance 这两个Node 时, 无法去自行输入 现有的模型名称 , 只能在默认的 五个模型中选择,  (如 llama3:8b-instrust-q4_K_M, 
 llama3   ,  phi3:3.8b-mini-instrust-4k-q4_K_m 等等 )   

而在 My Ollama Generate Node, 就可以自行输入 Model 名称,  如 qwen:7b  等

请问是有甚么操作错误的吗?  或者是My Ollama Generate Advance  与My Ollama Special Generate Advance , 原始设计就是不能修改.  请指教, 感谢
![ollama](https://github.com/wujm424606/ComfyUi-Ollama-YN/assets/7417165/60654969-4538-4c6e-9687-9a2b553c7878)

**Comment by wujm424606** [comment]
这个我主要是为了方便，以及防止一些使用者不知道使用怎么输入正确的名字，所以只设置了几个常用的，也就是可选项，方便使用者可以自己去选择，如果你觉得不方便的话，那我再把它改成可以自由输入名称的吧或者我再增添个可以自由输入名字的节点吧

**Comment by aigo-zc** [comment]
你好，我在我的工作流中设置了原节点，但是发现他只有默认五个节点，无法识别到我下载的qwen2模型
![Uploading CE7B34E786089E1DEFE40264BEC45154.png…]()

**Comment by aigo-zc** [comment]
想使用自己下载的模型导入非常困难，比如qwen2等等，能否设置为路径查找呢大佬

**Comment by wujm424606** [comment]
> 想使用自己下载的模型导入非常困难，比如qwen2等等，能否设置为路径查找呢大佬

我增加了一个extra_model选项，当extra_model的名字不为none的时候，会根据extra_model进行加载模型，此时前面的model无效，当extra_model的名字为none时，会根据前面选择的默认model进行加载

**Comment by git2306** [comment]
非常謝謝提供這麼好用的功能.

**Comment by aigo-zc** [comment]
> > 想使用自己下载的模型导入非常困难，比如qwen2等等，能否设置为路径查找呢大佬
> 
> 我增加了一个extra_model选项，当extra_model的名字不为none的时候，会根据extra_model进行加载模型，此时前面的model无效，当extra_model的名字为none时，会根据前面选择的默认model进行加载

非常感谢您的贡献
