### ISSUE TITLE
无法使用提示没有模型

### ISSUE THREAD

**Issue by mexifan** [wujm424606/ComfyUi-Ollama-YN#8]
Prompt outputs failed validation
OllamaGenerateAdvance:
- Value not in list: model: 'impactframes/llama3_ifai_sd_prompt_mkr_q4km:latest' not in ['llama3:8b-instruct-q4_K_M', 'llama3', 'phi3:3.8b-mini-instruct-4k-q4_K_M', 'phi3', 'phi3:3.8b-mini-instruct-4k-fp16']

ollama 里模型都下的，而且昨天还可以正常使用今天就不行了

**Comment by markawonge** [comment]
ollama list看下结果

**Comment by fge2016** [comment]
(base) root@ComfyUI-02:~# ollama list
NAME           	ID          	SIZE  	MODIFIED       
llama3.1:latest	42182419e950	4.7 GB	35 minutes ago	
llama3:latest  	365c0bd3c000	4.7 GB	46 minutes ago	
llava:latest   	8dd30f6b0cb1	4.7 GB	2 months ago

**Comment by wujm424606** [comment]
我进行了一次大的更新，现在手动分类后会自动加载已经下载的模型在模型列表里，也提供了删除模型的节点，详情可以看介绍文档
