### ISSUE TITLE
一直报错

### ISSUE THREAD

**Issue by shimianfeixingl** [wujm424606/ComfyUi-Ollama-YN#9]
![image](https://github.com/user-attachments/assets/f31440b3-0679-411b-8ed7-c1cd7bae5bd8)
这个是因为什么，我基本都是按着要求来下载和布置的，然后一直报错

**Comment by wujm424606** [comment]
最近我做了一次较大的更新，关于你的问题感觉和这个帖子里的问题一样，可以参考一下https://github.com/wujm424606/ComfyUi-Ollama-YN/issues/11
